### ISSUE TITLE
Two-way-sync

### ISSUE THREAD

**Issue by jochumdev** [matt-snider/todoist-taskwarrior#1]
Hi Matt,

I've added two-way-sync to `todoist-taskwarrior`, feel free to merge: https://git.webmeisterei.com/webmeisterei/todoist-taskwarrior/ if you want it here too.

Thanks for the great work!

**Comment by matt-snider** [comment]
Hi Rene,

Great work extending the tool to synchronize! Very happy this code could be useful for someone else :smile: .

I don't think I will merge your changes, because I actually intended this to be a _migration_ tool, and not a sync. After I got the tool functional (enough) I did a one-off migration and since then I no longer use Todoist. 

I will link to your repository in the README though! Thanks for reaching out!
